name: dart_postgres_example
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://innovationgroup.tech
# author: Kenneth Reilly <kennneth@innovationgroup.tech>

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  shelf: ^1.3.1
  dotenv: ^4.0.1
  postgres: ^2.4.5

dev_dependencies:
  pedantic: ^1.11.1
